### ISSUE TITLE
Incorrect chart generated if I change the line graph example to <month year> format

### ISSUE THREAD

**Issue by darylyu** [stewones/angular-morris-chart#11]
It works if I use the original example:

```
<div
line-chart
line-data='[
    { y: "2006", a: 100, b: 90 },
    { y: "2007", a: 75,  b: 65 },
    { y: "2008", a: 50,  b: 40 },
    { y: "2009", a: 75,  b: 65 },
    { y: "2010", a: 50,  b: 40 },
    { y: "2011", a: 75,  b: 65 },
    { y: "2012", a: 100, b: 90 }
]'
line-xkey='y'
line-ykeys='["a", "b"]'
line-labels='["Serie A", "Serie B"]'
line-colors='["#31C0BE", "#c7254e"]'>
</div>
```

But if I change the years to "month year":

```
<div
line-chart
line-data='[
    { y: "May 27", a: 100, b: 90 },
    { y: "May 28", a: 75,  b: 65 },
    { y: "May 29", a: 50,  b: 40 },
    { y: "May 30", a: 75,  b: 65 },
    { y: "May 31", a: 50,  b: 40 },
    { y: "June 1", a: 75,  b: 65 },
    { y: "June 2", a: 100, b: 90 }
]'
line-xkey='y'
line-ykeys='["a", "b"]'
line-labels='["Serie A", "Serie B"]'
line-colors='["#31C0BE", "#c7254e"]'>
</div>
```

It shows this:

![screen shot 2015-06-03 at 15 27 23](https://cloud.githubusercontent.com/assets/721919/7954802/4e8df4e8-0a05-11e5-9fdd-7ce25b021962.png)

**Comment by darylyu** [comment]
After reading Morris documentation, I guess this is the expected/documented behavior. 

http://morrisjs.github.io/morris.js/lines.html

Is `parseTime=false` supported by angular-morris-chart? Should I close this issue and open a new one if it's not supported or do we continue in this thread?

**Comment by stewones** [comment]
hi @darylyu 
unfortunately I did not map this attribute yet, but you can do it and send a PR. Just make sure that the tests are passing and let me know if you have any questions.

**Comment by stewones** [comment]
closing due inactivity
