### ISSUE TITLE
Can't set formatter for donut graph

### ISSUE THREAD

**Issue by rolaveric** [stewones/angular-morris-chart#15]
Looks like angular-morris-chart supports setting the 'data' and 'colors' options for donut charts, but not 'formatter' and 'resize'.
http://morrisjs.github.io/morris.js/donuts.html
I'd be willing to make a pull-request, just want to double check some of the details.

I assume for naming we'd stick with the 'donut-*' convention, so it'd be 'donut-formatter' and 'donut-resize'.

The formatter should be a function like '(item, data) => newLabel'.
I figure the input should be a reference to the function OR a filter name. eg. currency
So the logic would look something like this:
```js
if (typeof donutFormatter === 'function')
  options.formatter = donutFormatter;
else if (typeof donutFormatter === 'string' && $injector.has(donutFormatter + 'Filter'))
  options.formatter = $injector.get(donutFormatter + 'Filter');
```

**Comment by stewones** [comment]
Hi @rolaveric 
looks great, can you share a working sample in fiddle? it will be very usefully for the [docs](https://angular-morris-chart.stpa.co/)

**Comment by rolaveric** [comment]
Here we go: http://plnkr.co/edit/AsxnDG?p=preview
Had to make sure it only passes in the parameter to the filter.
You can see the changes at line 214 of `angular-morris-chart.js`.
I'll have a PR ready soon.

**Comment by stewones** [comment]
@rolaveric great job, but i was running into some problems here, I have just apply a patch into master, can you send a new PR?

**Comment by stewones** [comment]
@rolaveric one thing that I noticed is that you are using ['$injector'] for dependency injection, please replace with `/*@ngInject*/`, there is a gulp task to automate this

**Comment by stewones** [comment]
in this case, it would look like this
```
(function() {
    angular.module("angular.morris-chart").directive('donutChart', /*@ngInject*/ function($injector) {
```

**Comment by stewones** [comment]
Something that would not be too bad, is add the test to this new feature :smile:

**Comment by rolaveric** [comment]
No problem - I didn't notice you were using ng-annotate.
Can actually skip the `/*ngInject*/` annotation as ng-annotate will spot the "angular.module.directive()" method.
Which would you prefer?

I added unit tests and doco for the new feature already.
I could add an E2E test but it might be a bit flaky.

**Comment by stewones** [comment]
@rolaveric sorry i really didn't notice your test :sunglasses: thx. dont worry about e2e.

I've tested this here and all worked well with my last patch, let me know if not.
```js
(function() {
    angular.module("angular.morris-chart").directive('donutChart', /*@ngInject*/ function($injector) {
```

**Comment by stewones** [comment]
@rolaveric just waiting your new PR to merge, sorry, i didn´t understand well what you mean about "skip the `/*ngInject*`", i believe that you can use `/*ngInject*`" as i said, since the gulp task is already working perfectly

**Comment by rolaveric** [comment]
I've committed the changes to the branch and the PR has picked up on the new commits: https://github.com/stewones/angular-morris-chart/pull/16

**Comment by stewones** [comment]
@rolaveric merged. thx for contributing dude
cya :metal:
