### ISSUE TITLE
ng-click

### ISSUE THREAD

**Issue by goariel10** [stewones/angular-morris-chart#2]
Hi, is there a way to handle ng-clicks inside chart elements? if so how could i do it  ? .......

**Comment by stewones** [comment]
@goariel10 - what you mean about "inside chart elements" ? if you bind ng-click directly on directive, it should work. let me know if it does not.

**Comment by goariel10** [comment]
![sample](https://cloud.githubusercontent.com/assets/6316096/6192440/94185614-b377-11e4-9b15-1c04564f374a.png)

**Comment by stewones** [comment]
@goariel10 unfortunatly morris-chart does not support this trick
sorry.

**Comment by stewones** [comment]
closing this since the morris.js does not support this kind of feature. but if anyone has any ideas , please PR.

**Comment by Vahn84** [comment]
It does support the hover feature though

It would be great if this kind of feature could have been reproduced as an ng-click in angularjs

**Comment by anupalhub** [comment]
@Vahn84 How do we use it in Angular? Can we give custom $scope function?

**Comment by Vahn84** [comment]
@anupalhub sorry mate, 2 years has passed, I don't really remember that T_T

**Comment by anupalhub** [comment]
@st1s Any help ?

**Comment by stewones** [comment]
Sorry guys, angularjs is deprecated. I will make the morris  module for angular 2 soon, what will be better to address issues like this
