### ISSUE TITLE
Non-date fields in a line chart cause Error: Invalid value for <path> attribute d="M,0,0"

### ISSUE THREAD

**Issue by venkatramachandran** [stewones/angular-morris-chart#23]
Using any non-date field in morris causes `Error: Invalid value for <path> attribute d="M,0,0"` as raphael tries to coerce these values into dates, as mentioned in [1](http://stackoverflow.com/questions/30450906/angular-morris-js-not-working-for-non-dates) and [2](http://stackoverflow.com/questions/21833599/backbone-collection-into-morris-js-d-m-0-0-error).

To fix this, `parseDate` attribute needs to be exposed by the lineChart directive so that the users can set it to `false`.

**Comment by venkatramachandran** [comment]
#22 fixes this.

**Comment by stewones** [comment]
nice job, thx.
