### ISSUE TITLE
Unable to change labels/keys dynamically

### ISSUE THREAD

**Issue by venkatramachandran** [stewones/angular-morris-chart#25]
We have a dashboard where we use angular-morris-chart to display various graphs, with the user being able to change the graph data dynamically. When such a change is initiated, we need to change the xkey/ykeys/lineData/lineColors. 
With the current implementation, changing only the lineData is allowed. I've proposed a fix in PR #24 . Please review and merge.

**Comment by stewones** [comment]
merged @venkatramachandran 
thx
