### ISSUE TITLE
Behave Like Line feature for area charts

### ISSUE THREAD

**Issue by spry-rproud** [stewones/angular-morris-chart#29]
Support for the newer [behaveLikeLine](https://morrisjs.github.io/morris.js/lines.html#areas) flag on area charts would be useful.

**Comment by stewones** [comment]
@spry-rproud sorry for delay. i'm very busy but will patch this new feature asap

**Comment by stewones** [comment]
@spry-rproud solved by PR #30 check in master
thx to @rolaveric
