### ISSUE TITLE
Strange behaviour/non-function when combining charts with UI Bootstrap.

### ISSUE THREAD

**Issue by tomatolicious** [stewones/angular-morris-chart#31]
I'm trying to use angular-morris-chart together with [Angular UI Bootstrap](https://angular-ui.github.io/bootstrap/), which works fine in most cases when placed on the page normally.

Once the charts are included in certain elements such as tabbed controls or modals, the charts don't draw properly anymore. They still draw the hoverstate and those even react to moving your mouse over the invisible graph.

![chat error](https://i.imgur.com/wenJGUa.png)

I made a Plunker demonstrating this here:

http://plnkr.co/edit/GRIRu7B7yaEFKeMhzAMY?p=preview

**Comment by okdas** [comment]
That is not angular-morris-chart issue. I have the same problem with raw morris.js usage.

**Comment by stewones** [comment]
Thx @okdas
