### ISSUE TITLE
Documentation and Examples

### ISSUE THREAD

**Issue by semaja2** [stewones/angular-morris-chart#32]
Hi Guys,

I have been using MorrisJS in other projects with out angular and thought it would be good to use your AngularJS version, however I am having trouble migrating my code to your syntaxes and found that whilst some features have been added according to change logs, the documentation and examples do not reflect these features

Could we please get some examples or assistance in using the below options?

````
window.graph = Morris.Bar({
        element: 'timesheet-chart',
        data: data.week,
        xkey: ['date'],
        xLabels: 'day',
        ymin: 0,
        ykeys: ['logged'],
        labels: ['Hours Logged'],
        hideHover: false,
        xLabelMargin: 10,
        xLabelAngle: 0,
        xLabelFormat: function(date) {
          var weekday = new Array(7);
          weekday[0]=  "Sunday";
          weekday[1] = "Monday";
          weekday[2] = "Tuesday";
          weekday[3] = "Wednesday";
          weekday[4] = "Thursday";
          weekday[5] = "Friday";
          weekday[6] = "Saturday";

          var dt1   = parseInt(date.label.substring(0,2));
          var mon1  = parseInt(date.label.substring(3,5));
          var yr1   = parseInt(date.label.substring(6,10));
          var d = new Date(yr1, mon1-1, dt1);
          return weekday[d.getDay()];
        },
        dateFormat: function(date) {
          d = new Date(date);
          return d.getDate()+'-'+(d.getMonth()+1)+'-'+d.getFullYear();
          },
        barColors: function(row,series,type){
          if (series.index == 0) {
            if(row!=undefined && row.y<4){
              return "#a94442"; // danger
            } else if (row.y < 7.5) {
              return "#8a6d3b"; // warning
            } else {
              return "#31708f"; // success
            }
          } else {
            return "#31808f"; // success
          }
        },
        resize: true
      });
    }
````

**Comment by stewones** [comment]
Hi @semaja2 

can you paste some piece of code? 
are you using the lib from [master branch](https://github.com/stewones/angular-morris-chart/blob/master/src/angular-morris-chart.min.js)?

**Comment by semaja2** [comment]
I am using the code from https://angular-morris-chart.stpa.co with the examples on that page which would be as below

````
<div
bar-chart 
bar-data='[
    { y: "2006", a: 100, b: 90 },
    { y: "2007", a: 75,  b: 65 },
    { y: "2008", a: 50,  b: 40 },
    { y: "2009", a: 75,  b: 65 },
    { y: "2010", a: 50,  b: 40 },
    { y: "2011", a: 75,  b: 65 },
    { y: "2012", a: 100, b: 90 }
]'
bar-x='y'
bar-y='["a", "b"]'
bar-labels='["Series A", "Series B"]'
bar-colors='["#31C0BE", "#c7254e"]'>
</div>
````

**Comment by stewones** [comment]
which version of angular-morris you are using?

its important to know because we recently had some breaking changes to easily support all the features of morris.js lib

**Comment by stewones** [comment]
sorry but i still have to update the online documentation.

you can try the version of master branch with the same properties of morris.js lib

**Comment by semaja2** [comment]
When you say try the same properties do you mean to use the <div bar-chart bar-property> or should I be using Javascript?

Can I simply create a JS object with the options defined and then apply them using <div bar-chart bar-options="jsObject">

**Comment by stewones** [comment]
@semaja2 take a look at [this plnkr](http://plnkr.co/edit/20ASpi?p=preview)

**Comment by semaja2** [comment]
Thanks works a treat, looks like some of the undocumented Morris.JS options are missing as well eg. xLabelFormat for Bar Charts

Would it be possible to make it future proof that rather then looking at a list of known keys, it simply looks at anything prefixed with "bar-" and uses them?

**Comment by stewones** [comment]
@semaja2 I believe that this issue has been improved, by now we mapping all Morris.js keys in a simple array. (eg. take a look at [this file](https://github.com/stewones/angular-morris-chart/blob/master/src/lib/directives/areaChart.directive.js#L32).)



[the plnkr](http://plnkr.co/edit/20ASpi?p=preview) just uses a  [minifed version](https://github.com/stewones/angular-morris-chart/blob/master/src/angular-morris-chart.min.js) of master branch. will release a new version for angular-morris asap.

**Comment by stewones** [comment]
version 1.2.0 released. just install it by bower or npm.
