### ISSUE TITLE
Bower update generic options loader

### ISSUE THREAD

**Issue by GGMoreno** [stewones/angular-morris-chart#33]
Hi! congratulations for angular-morris-charts!

I'm using your code in a project with bower. When I do bower update I'm in 1.10 version but the code has not got the new generic options loader feat. I did uninstal and  and unistall again. 

Probably I'm missing something. Thank you!

**Comment by stewones** [comment]
hi @GGMoreno 
try `bower install angular-morris-chart#master`

**Comment by GGMoreno** [comment]
Thank you! Works perfectly :)
