### ISSUE TITLE
Bar chart unit issue.

### ISSUE THREAD

**Issue by zhenshan1984** [stewones/angular-morris-chart#34]
Hi, Cound you add in the other attributes like 'parseTime, postUnits, preUnits, Units' as in directive 'areaChart', I tried the preUnits, it actually works for barChart, those in morries.js documentation, it is not existed.

**Comment by stewones** [comment]
@zhenshan1984 look #35

**Comment by zhenshan1984** [comment]
Hi, I know it is working for line-chart, but I am refer to bar-chart, it is not working with bar-pre-unit / pre-unit.

**Comment by stewones** [comment]
@zhenshan1984 unfortunately it seems that this feature does not exist in Morris

https://morrisjs.github.io/morris.js/bars.html

Our lib for angular only works with oficial API of Morris

**Comment by stewones** [comment]
Sample usage for working with postUnit

https://jsfiddle.net/stewones/n6aaLckb/

**Comment by zhenshan1984** [comment]
Thanks.
