### ISSUE TITLE
Does not identify the value of x

### ISSUE THREAD

**Issue by Isaac6702** [stewones/angular-morris-chart#39]
Hi,
I have the following settings:
`        <div
            bar-chart
            bar-data='transactions'
            bar-x='sender.username'
            bar-y='["amount"]'
            bar-labels='["Monto"]'
            line-colors='["#31C0BE", "#c7254e"]'>
        </div>`
and my json so:
`"transactions": [
    {
      "id": 55,
      "amount": 500,
      "sender": {
        "id": 4,
        "username": "admin@xxxx.com"
      },
      "receiver": {
        "id": 3,
        "username": "user1@xxxx.com"
      }
    },
    {
      "id": 26,
      "amount": 10000,
      "type": "MAPAY",
      "sender": {
        "id": 4,
        "username": "user2@xxxx.com"
      },
      "receiver": {
        "id": 3,
        "username": "user1@xxxx.com"
      }
    }
  ]`

the problem I have is that in the "x" always shows undefine to paracer not recognize "sender.username" I can do?

**Comment by stewones** [comment]
Hi @Isaac6702 

i am closing because that has nothing to do with angular-morris lib

anyway maybe you can fix by looking this samples

https://jsfiddle.net/stewones/zwb207md/
https://jsfiddle.net/stewones/n6aaLckb/

**Comment by Isaac6702** [comment]
if it has to do with angular morris, then that?

2016-02-19 10:36 GMT-04:30 Stewan Pacheco <notifications@github.com>:

> Hi @Isaac6702 <https://github.com/Isaac6702>
>
> i am closing because that has nothing to do with angular-morris lib
>
> anyway maybe you can fix by looking this samples
>
> https://jsfiddle.net/stewones/zwb207md/
> https://jsfiddle.net/stewones/n6aaLckb/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stewones/angular-morris-chart/issues/39#issuecomment-186250802>
> .
>



-- 
Isaac Arismendi.
