### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by Isaac6702** [stewones/angular-morris-chart#40]
hi,
Is there any way to format a timestamp with angular-morris?

**Comment by stewones** [comment]
yes you can
https://github.com/stewones/angular-morris-chart/search?utf8=%E2%9C%93&q=dateFormat

**Comment by stewones** [comment]
@Isaac6702 you can try this way
https://jsfiddle.net/stewones/q8mcqm8k/

Feel free to open new issues

**Comment by mpk2** [comment]
Perhaps I'm misunderstanding this, but I don't see anything about `dateFormat` in the docs, and when I looked at the code, it would seem to ignore any function (not a string). I've tried also angular date filter parameters such as `'MM-DD-YYYY'` with no luck.

**Comment by st1s** [comment]
hi @mpk2 

recently i did changes in my username at some services which led to break of some links. take a look at this fiddle https://jsfiddle.net/st1s/q8mcqm8k/

thanks for using angular-morris

**Comment by mpk2** [comment]
Perfect, thanks! I see that you prepend 'line' to the properties now for the directive.
