### ISSUE TITLE
onClick event on Donut Chart

### ISSUE THREAD

**Issue by trangchuvn** [stewones/angular-morris-chart#41]
Hello guy. Thank you for your angular-morris-chart directive, it's very nice. Can you help me how to call onclick event on the Donut Chart?

**Comment by stewones** [comment]
Hi @trangchuvn 

Events are limited. What you can do is target a click event on all element that contains the morris instance.

Like in this fiddle sample https://jsfiddle.net/stewones/bnssx7pc/

I'll close but feel free to reopen
