### ISSUE TITLE
bar-x not fetching value from $scope

### ISSUE THREAD

**Issue by filipeaguiar** [stewones/angular-morris-chart#42]
I have a function that fetches a json using $http.get. On success, I execute this code:
>$scope.ocupacao = data;
>$scope.xaxis = 'mes';
>$scope.yaxis = ['txo'];
>$scope.label = ['Taxa de Permanência'];

Where `mes` and `txo` are the only keys of the json.

When I call, from the html, `{{xaxis}}` and `{{yaxis}}` they show `mes` and `txo` correctly, but when I use:
>bar-x = 'xaxis'
>bar-y = 'yaxis'

Only the second resolves to the correct value and the bar-chart shows `undefined` on the X axis. But if I, manualy, write:
>bar-x = 'mes'

The bar-chart shows the value properly.

**Comment by stewones** [comment]
hi @filipeaguiar 

i didnt understand your issue.

can you share a fiddle with your use-case ?

**Comment by filipeaguiar** [comment]
It's basically this:

When I use `bar-x="xaxis"` the labels at the bottom of the chart appears as _undefined_
When I use `bar-x="mes"`, they appear normal, showing month names
Even when ``{{xaxis}}`` returns `mes` within the same controller.

I'm not very familiar with jsfiddle, but I can give it a try if you didn't understand this time.

**Comment by stewones** [comment]
hi @filipeaguiar can you fork and reproduce by this [fiddle](https://jsfiddle.net/stewones/zwb207md/) ?

**Comment by filipeaguiar** [comment]
I'll try and post the results later. BTW, I'm using Angular 1.5.0, could this be the problem?

**Comment by stewones** [comment]
I dont think so. the fiddle above uses 1.5.0-rc.1

**Comment by filipeaguiar** [comment]
Ok, I did the fiddle, here it is:
https://jsfiddle.net/68L1xp4u/

**Comment by stewones** [comment]
@filipeaguiar do not see anything new, can you double check your fiddle? are you applying your changes?

We try to map all morris options. If there is something missing, please create a new issue.

**Comment by filipeaguiar** [comment]
Sorry, as I told you, I'm not familiar with jsfiddle. But this is the updated code:
[bar-x attribute problem](https://jsfiddle.net/68L1xp4u/2/)

**Comment by stewones** [comment]
@filipeaguiar got it

in this case you have to pass the var with brackets {{}}
eg.: https://jsfiddle.net/stewones/0qqs6rhb/

**Comment by filipeaguiar** [comment]
Thank you, it worked. But this should be listed in the documentation.

**Comment by stewones** [comment]
@filipeaguiar np :beers: 

in fact this is a ng 1.x issue rather than our lib. anyway [pr´s](https://github.com/stewones/angular-morris-chart/blob/master/CONTRIBUTING.md) are always welcome
