### ISSUE TITLE
Tooltips issue

### ISSUE THREAD

**Issue by frlinw** [stewones/angular-morris-chart#43]
Hi,

In my app and in your jsfiddle exemple, tooltips doesn't work fine

https://jsfiddle.net/stewones/n6aaLckb/

**Comment by stewones** [comment]
Hi @frlinw 

what exactly you mean?

because the result of my jsfiddle is exactly the same of jsbin from Morris.js doc

my fiddle
https://jsfiddle.net/stewones/n6aaLckb/

jsbin morris
http://jsbin.com/uqawig/441/embed?js,output

I'll close but feel free to open a new issue if is necessary
