### ISSUE TITLE
Custom dateFormat and xLabelFormat function

### ISSUE THREAD

**Issue by skol-pro** [stewones/angular-morris-chart#45]
Hi !

All in the title, how can I pass custom functions to those 2 options ?
I tried by simply passing **date-format="scope.fooFunction"** but it doesn't work, I just get the following error:

`Cannot read property 'match' of undefined`

**Comment by skol-pro** [comment]
Not maintained any more ?

**Comment by stewones** [comment]
all features are ok . you probably doing something wrong. if you can play your use case in the fiddle or equivalent , would be more easier to help

**Comment by skol-pro** [comment]
Ah so you're sure that passing a reference to a function like I did using the **date-format** param should works ?

**Comment by stewones** [comment]
@skol-pro you can try this way
https://jsfiddle.net/stewones/q8mcqm8k/

I'll close but feel free to reopen.

**Comment by skol-pro** [comment]
Finally found the source of my problem, I had to replace:
`line-xkey="ctrl.foo.xkey"`
by:
`line-xkey="{{ctrl.foo.xkey}}"`

There is no eval or something in the directive.

**Comment by skol-pro** [comment]
Looks like the same is happening for `dateFormat` and `xLabelFormat` functions, they aren't existing in **options**, so no injects in `processFilterOptions` function.

**Comment by skol-pro** [comment]
@stewones Same for resize actually, weird. There is no ways to pass an morris configuration object instead of defining all those html attributes by the way ?

**Comment by stewones** [comment]
@skol-pro as described in README, this is a directive, not a service. so you should use in angular directives way, with attributes.
