### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ln206** [stewones/angular-morris-chart#47]
**EDIT:** it was a mistake on my part, I should have played around more with the directive before making an issue here, I changed the value of `bar-y` to `["y"]`, I also added `bar-labels` in there, and it worked. Sorry about this.

First of all, I would like to apologize because English is not my native language, so there are mistakes and typos here and there.

I'm trying to make a bar chart, but I only want 1 column for every x (or label or w.e you call it), is this how you do it? because I'm getting the error above (this issue's title). Or maybe the bar chart doesn't even support that.

I have a data formatted as follow:

` $scope.data = [{
     x: "choice 1", y: 2
 },{
     x: "choice 2", y: 6
 },{
     x: "choice 3", y: 12
 }]`

Here's the directive:

`<div
       bar-chart
       bar-data='data'
       bar-x='x'
       bar-y='y'
       bar-colors='["#31C0BE", "#c7254e"]'>
 </div>`

Please let me know, thank you.

**Comment by stewones** [comment]
Hi @ln206 

there is no problem . It would be more easier to help if you reproduce your issue in tools Like fiddle , codepen , etc.

**Comment by stewones** [comment]
I will close due to inactivity
