### ISSUE TITLE
How to use parseTime:False in angular-morris-chart

### ISSUE THREAD

**Issue by diggudg** [stewones/angular-morris-chart#51]
I using morris chart in many jquery project and have used parseTime and it's working perfectly in jquery but I'm not able to use same in angular project.
so, please help to use use parseTime in angular.
below is my code what I have used in my project
` <div area-chart
                                 area-post-units="''"
                                 area-data='data'
                                 area-xkey='TimeInterval'
                                 area-ykeys='["KYCCount", "eKYCCount"]'
                                 area-labels='["KYC Count", "eKYC kCount"]'
                                 area-colors='["#31C0BE", "#c7254e"]'
                                 area-parseTime="false">
                            </div>`

**Comment by Tronix117** [comment]
Try to use `area-parse-time="false"` instead of `area-parseTime="false"` ;)

**Comment by stewones** [comment]
Hi @diggudg

In the most of cases the problem is on way you write angular 1.x attributes.

try with dashes - as @Tronix117 says.


I'll close but feel free to ask
