### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by alexlopesbn** [stewones/angular-morris-chart#6]
C:\Users\Alex\git\bjj-server-client>npm install angular-morris-chart --save
npm WARN package.json bjj-server-clint@0.0.1 No description
npm WARN package.json bjj-server-clint@0.0.1 No repository field.
npm WARN package.json bjj-server-clint@0.0.1 No README data
npm WARN package.json karma-coverage@0.2.7 No README data
npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
npm WARN package.json path@0.4.10 path is also the name of a node core module.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "angular-morris-chart" "--save"
npm ERR! node v0.12.0
npm ERR! npm v2.5.1
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: morris.js@'>=0.5.1 <0.6.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.5.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Alex\git\bjj-server-client\npm-debug.log
C:\Users\Alex\git\bjj-server-client>node -v
v0.12.0
C:\Users\Alex\git\bjj-server-client>npm -v
2.5.1

anyone have any solution?

**Comment by stewones** [comment]
it seems that some dependencies are broken, I'm out of time to give a refact in the project and add some tests. anyway you can use the minified library [here](https://github.com/stewones/angular-morris-chart/blob/master/src/angular-morris-chart.min.js)
