### ISSUE TITLE
Morris charts all throwing error

### ISSUE THREAD

**Issue by lombardi-gux** [stewones/angular-morris-chart#7]
I followed the instructions for my angular 1.3.15 app.  I installed the package via bower and then linked the JS file in my index.html and the module injection in my app.js.

On the page I want the chart to appear, I took one of the examples (donut and also bar) and pasted into the page grid.

I get this error:

````
ReferenceError: Morris is not defined
    at Object.fn (angular-morris-chart.min.js:27)
    at Scope.$get.Scope.$digest (angular.js:14308)
    at Scope.$get.Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)
````

the graph is supposed to be in a view state that's described like so: 
````
  .state('graphs.lib1', {
      url: '/lib1',
      templateUrl: 'modules/graphs/templates/graphs-lib1.html',
      controller: 'Lib1Controller as lib1'
    })
````

The controller itself, so far, is empty.

**Comment by aarthipa** [comment]
I see the same error. This issue is closed?

**Comment by stewones** [comment]
@aarthipa could you try from master branch ?

maybe Morris.js lib is not loaded before?

**Comment by akshayamoorthy** [comment]
Include 
 'raphael/raphael.js', 'morris.js/morris.js', 'angular-morris-chart/src/angular-morris-chart.js'
These files will be in your bower_components after the bower install .
