### ISSUE TITLE
Documentation does not include morris.js as part of installation

### ISSUE THREAD

**Issue by AviEt** [stewones/angular-morris-chart#8]
Following the documentation I added angular-morris-chart.min.js to my app and added the 'stpa.morris' as a dependency. After the directives didn't work with the an exception "Morris is not defined" I added the dependencies needed for using Morris with plain jquery (raphael-min.js and morris.min.js. Already had jquery) and it solved the problem.

I suggest adding this to the documentation just to spare some time for first-timers.

**Comment by stewones** [comment]
@AviEt 
it is documented on bower and npm packages, dependencies must be installed by them. i will investigate and patch  asap
