### ISSUE TITLE
Problem showing a graph in a bootstrap modal

### ISSUE THREAD

**Issue by olaznog10** [stewones/angular-morris-chart#9]
Is there any problem showing a morrisjs graph in a Modal? 

I'm traying to show a graph in a bootstrap modal but it doesn't work. It just show the hover pop-up even if you quit the z-index value.

Thanks in advance.

**Comment by stewones** [comment]
@olaznog10 you can play a piece of code in jsfiddle?

**Comment by stewones** [comment]
closing due inactivity
